apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment  # Specify the name of the deployment
  namespace: yolo-app  # Add the namespace
spec:
  replicas: 1  # Set the desired number of pod replicas
  selector:
    matchLabels:
      app: backend  # Define the label selector to match pods with the label 'app: backend'
  template:
    metadata:
      labels:
        app: backend  # Label the pods created by this deployment with 'app: backend'
    spec:
      containers:
      - name: backend  # Assign a name to the container
        image: maukujnr/yolo-backend-image:v1.1  # Specify the Docker image and version
        env:  # Add hardcoded MongoDB host and port
        - name: MONGODB_HOST
          value: mongodb-service  # Service name for MongoDB
        - name: MONGODB_PORT
          value: "27017"  # MongoDB port
        resources:
          requests:
            memory: "64Mi"  # Define the minimum memory request for the container
            cpu: "250m"  # Define the minimum CPU request for the container
          limits:
            memory: "128Mi"  # Set the maximum memory limit for the container
            cpu: "500m"  # Set the maximum CPU limit for the container
        ports:
        - containerPort: 8080  # Define the port on which the container will listen

# The following section defines the Service for the backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service  # Specify the name of the service
  namespace: yolo-app  # Add the namespace
spec:
  selector:
    app: backend  # Define the label selector to route traffic to pods with the label 'app: backend'
  ports:
    - protocol: TCP
      port: 80  # Define the port through which the service will be accessed
      targetPort: 8080  # Specify the target port on the pods where traffic will be forwarded
  type: LoadBalancer  # Use a LoadBalancer service type to expose the service to the internet
